version: '3'

services:
    skakeboard-park:
        environment: 
            POSTGRES_USER: 
            POSTGRES_PASSWORD: 
            POSTGRES_DB: 
            POSTGRES_HOST: 
            NODE_ENV: production
            PORT: 8080
        depends_on: 
            - postgres
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: "tecky-capstone-backend-server:latest"
        ports:
            - "8080:8080"
    